In [3]:
# creating the heart health predictor
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# rendering data
dataset = pd.read_csv('heart.csv')
dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
dataset.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [6]:
dataset.shape

(303, 14)

In [7]:
dataset['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

here

1---> unhealthy heart

2---> healthy heart

In [8]:
# there is no major difference in target value
# spliting the data
x= dataset.drop(columns='target',axis=1)
y= dataset['target']

print(x)
x.shape

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

(303, 13)

In [9]:
print(y)
y.shape

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

(303,)

In [10]:
# train_test_split data for traing model
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, stratify=y, random_state=2)

In [11]:
# using logistic lib to make data shorted
model = LogisticRegression()
train_data = model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
# accuracy test
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.8512396694214877

In [13]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.819672131147541

In [14]:
# creating prediction system

imput_data =(38,1,2,138,175,0,1,173,0,0,2,4,2)

# converting input data in array because data is in tuple form

data_array = np.asarray(imput_data)

# reshaping of array

reshaped_data = data_array.reshape(1,-1)

prediction = model.predict(reshaped_data)
print(prediction)


if prediction[0]== 0:
    print('The Person does not have a unhealthy heart and diseased found')
else:
    print('The Person have a healthy heart and no diseased found ')

[1]
The Person have a healthy heart and no diseased found

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [15]:
import pickle

In [17]:
filename = 'heart_health.sav'
pickle.dump(model, open(filename, 'wb'))

In [18]:
loaded_data = pickle.load(open('heart_health.sav', 'rb'))

In [19]:
# creating prediction system

imput_data =(38,1,2,138,175,0,1,173,0,0,2,4,2)

# converting input data in array because data is in tuple form

data_array = np.asarray(imput_data)

# reshaping of array

reshaped_data = data_array.reshape(1,-1)

prediction = model.predict(reshaped_data)
print(prediction)


if prediction[0]== 0:
    print('The Person does not have a unhealthy heart and diseased found')
else:
    print('The Person have a healthy heart and no diseased found ')

[1]
The Person have a healthy heart and no diseased found

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(